### ISSUE TITLE
请问渐进式 olap 能带来哪些好处呢，在什么场景下发现有渐进式 olap 的需求？

### ISSUE THREAD

**Issue by xzhangxian1008** [lealone-plugins/lealone-olap#1]

**Comment by codefollower** [comment]
把它想像成 JVM 的字节码解释器、C1 编译器、C2 编译器就好理解了，
执行一条 SQL 时并不能确定涉及多少条记录，所以第一步用解释器的方式执行 SQL，
如果执行了一段时间 SQL 还没结束，那大概率这是个耗时的  SQL，所以第二步把 SQL 编译成本地代码执行，这就是渐进式。

**Comment by xzhangxian1008** [comment]
> 把它想像成 JVM 的字节码解释器、C1 编译器、C2 编译器就好理解了， 执行一条 SQL 时并不能确定涉及多少条记录，所以第一步用解释器的方式执行 SQL， 如果执行了一段时间 SQL 还没结束，那大概率这是个耗时的 SQL，所以第二步把 SQL 编译成本地代码执行，这就是渐进式。

我的理解是渐进式 olap 主要用于减少 sql 本地编译的开销，但是现在db会针对常用的sql做缓存，所以我觉得 sql 编译的开销应该没有那么大吧。

**Comment by codefollower** [comment]
编译和执行都受影响的，OLAP 引擎一般是按批获取记录，然后按列运算，如果记录很少的时候 OLAP 引擎的执行速度不一定比 OLTP 引擎快的。

**Comment by codefollower** [comment]
如果一条 select 语句已经 prepared 了，第二次查询若是只涉及一条记录，OLTP 引擎取一条记录就好了，OLAP 引擎读了一批记录，这时当然是用 OLTP 引擎执行得更快。

**Comment by xzhangxian1008** [comment]
明白了，感谢回答。
